name: period_tracker
description: A menstrual cycle tracking app

publish_to: 'none'

version: 1.0.8

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  table_calendar: ^3.0.9
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0+3
  timezone: ^0.10.1
  yandex_mobileads: ^7.18.0
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.5.2
  http: ^1.2.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/